export const NORMAL_ORDERS="NORMAL_ORDERS"
export const VIP_ORDERS="VIP_ORDERS"
export const PENDING_ORDERS="PENDING_ORDERS"
export const PROCESSED_PENDING_ORDERS="PROCESSED_PENDING_ORDERS"
export const COMPLETED_ORDERS="COMPLETED_ORDERS"
export const ADD_BOTS="ADD_BOTS"
export const REMOVE_BOTS="REMOVE_BOTS"




